---
cluster:
  children:
    k3s_init:
      hosts:
        rp-node-1:
          ansible_host: 192.168.1.230
    k3s_join:
      hosts:
        rp-node-2:
          ansible_host: 192.168.1.231
        rp-node-3:
          ansible_host: 192.168.1.232
  vars:
    ansible_user: dark
    ansible_python_interpreter: /usr/bin/python3
